version: "3.9"
services:
    rabbitmq:
    platform: linux/arm64
    image: rabbitmq:3.11-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
